//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FileRepository.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Storage
    {
        public Storage()
        {
            this.MyUsersStoreLinks = new HashSet<MyUsersStoreLink>();
            this.Storage11 = new HashSet<Storage>();
            this.Storages1 = new HashSet<Storage>();
            this.Storage12 = new HashSet<Storage>();
            this.Storages2 = new HashSet<Storage>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string SType { get; set; }
        public string ClientLocation { get; set; }
        public string ServerLocation { get; set; }
        public string ContainsFile { get; set; }
        public string ContainsFolder { get; set; }
        public string Size { get; set; }
        public string CreatedOn { get; set; }
        public string UpdatedOn { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
        public string ReadAccess { get; set; }
        public string WriteAccess { get; set; }
        public string IsHidden { get; set; }
        public string IsSharing { get; set; }
    
        public virtual ICollection<MyUsersStoreLink> MyUsersStoreLinks { get; set; }
        public virtual ICollection<Storage> Storage11 { get; set; }
        public virtual ICollection<Storage> Storages1 { get; set; }
        public virtual ICollection<Storage> Storage12 { get; set; }
        public virtual ICollection<Storage> Storages2 { get; set; }
    }
}
